name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install core dependencies only
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install requests
        pip install numpy
        pip install scikit-learn
        pip install nltk
        pip install customtkinter
        pip install pillow
        pip install pyautogui
        pip install psutil
        pip install pygetwindow
        pip install pymsgbox
        pip install pyperclip
        pip install keyboard
        pip install mouse
        pip install matplotlib
        pip install pandas
    
    - name: Test basic functionality
      run: |
        echo "Testing Python version..."
        python -c "import sys; print('Python version:', sys.version)"
        
        echo "Testing core imports..."
        python -c "import numpy; print('NumPy imported successfully')"
        python -c "import requests; print('Requests imported successfully')"
        python -c "import customtkinter; print('CustomTkinter imported successfully')"
        python -c "import pytest; print('Pytest imported successfully')"
        
        echo "Running basic tests..."
        pytest tests/test_basic.py -v --tb=short
        pytest tests/test_minimal.py -v --tb=short
        pytest tests/test_super_simple.py -v --tb=short
        pytest tests/test_ultra_simple.py -v --tb=short
        
        echo "All tests completed successfully!"

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package
      run: |
        twine check dist/*
